import { Error } from '@seventech/shared'
import Head from 'next/head'
import React from 'react'

export default function ErrorPage() {
  return (
    <>
      <Head>
        <title>SevenTech | Error</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Error />
    </>
  )
}